# Generated by Django 3.2.7 on 2021-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите ингредиент', max_length=250, verbose_name='Название ингредиента')),
                ('amount', models.PositiveIntegerField(help_text='Укажите ингредиент', verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения', max_length=250, verbose_name='Единица измерения')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
