# Generated by Django 3.2.7 on 2021-09-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
    ]
