# Generated by Django 3.2.7 on 2021-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение рецепта', null=True, upload_to='recipes/images/', verbose_name='Изображение рецепта'),
        ),
    ]
