# Generated by Django 3.2.7 on 2021-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите тэг', max_length=150, unique=True, verbose_name='Название тэга')),
                ('color', models.BinaryField(help_text='Укажите цвет в формате HEX-кода', max_length=6, unique=True, verbose_name='HEX-код цвета')),
                ('slug', models.SlugField(help_text='Укажите слаг тэга', unique=True, verbose_name='Слаг')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
