# Generated by Django 3.2.7 on 2021-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Укажите цвет в формате HEX-кода', max_length=7, unique=True, verbose_name='HEX-код цвета'),
        ),
    ]
