# Generated by Django 3.2.7 on 2021-09-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
 
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите ингредиент', max_length=250, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения', max_length=250, verbose_name='Единица измерения')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default='0', help_text='Укажите количество', verbose_name='Количество')),
                ('ingredients', models.ForeignKey(help_text='Укажите ингредиенты', on_delete=django.db.models.deletion.PROTECT, related_name='ingredientsamount', to='recipes.ingredient', verbose_name='Ингредиенты')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите тэг', max_length=150, unique=True, verbose_name='Название тэга')),
                ('color', models.CharField(help_text='Укажите цвет в формате HEX-кода', max_length=7, unique=True, verbose_name='HEX-код цвета')),
                ('slug', models.SlugField(help_text='Укажите слаг тэга', unique=True, verbose_name='Слаг')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название рецепта', max_length=150, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Напишите рецепт', verbose_name='Рецепт')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение рецепта', null=True, upload_to='recipes/', verbose_name='Изображение рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Укажите время приготовления', verbose_name='Время приготовления')),
                ('author', models.ForeignKey(help_text='Выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(help_text='Укажите ингредиенты', related_name='recipes', through='recipes.IngredientAmount', to='recipes.Ingredient', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(blank=True, help_text='Укажите тэг', related_name='recipes', to='recipes.Tag', verbose_name='Тэг')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(help_text='Укажите рецепт', on_delete=django.db.models.deletion.PROTECT, related_name='ingredientsamount', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
