# Generated by Django 3.2.7 on 2021-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210929_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(help_text='Укажите количество', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Укажите время приготовления', verbose_name='Время приготовления'),
        ),
    ]
