# Generated by Django 3.2.7 on 2021-09-29 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210929_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(help_text='Укажите количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
