# Generated by Django 3.2.7 on 2021-09-29 12:40

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Укажите время приготовления', validators=[recipes.validators.validate_cooking_time], verbose_name='Время приготовления'),
        ),
    ]
