# Generated by Django 3.2.7 on 2021-09-29 12:41

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(help_text='Укажите количество', validators=[recipes.validators.validate_amount], verbose_name='Количество'),
        ),
    ]
