# Generated by Django 3.2.7 on 2021-09-16 15:31

from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210916_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(help_text='Укажите время приготовления', validators=[recipes.models.validate_cooking_time], verbose_name='Время приготовления'),
        ),
    ]
