# Generated by Django 3.2.7 on 2021-09-16 16:38

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210916_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(help_text='Укажите количество', validators=[recipes.models.validate_amount], verbose_name='Количество'),
        ),
    ]
