# Generated by Django 3.2.7 on 2021-09-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписчики', 'verbose_name_plural': 'Подписчик'},
        ),
    ]
